<?php
return [
    'core_hero' => [
        'pre_headline' => 'Meet Core',
        'headline' => 'The AI Engine That <span class="text-accent">Changes Everything.</span>',
        'subtitle' => 'Core is our proprietary AI engine that learns your business, remembers everything, and helps us build marketing that actually sounds like you — and converts like crazy.',
        'cta_primary' => 'See Core in Action',
        'cta_secondary' => 'Talk to Our Team',
    ],
    'core_problem' => [
        'pre_headline' => 'The Problem',
        'headline' => 'Why Does Every Marketing Agency <span class="text-accent">Feel the Same?</span>',
        'month1_label' => 'Month 1',
        'month1_text' => 'They ask you a thousand questions. You spend hours explaining your business.',
        'month2_label' => 'Month 3',
        'month2_text' => 'New account manager. You explain everything again.',
        'month3_label' => 'Month 6',
        'month3_text' => 'The content they\'re producing sounds generic. Could be for any business in any city.',
        'month4_label' => 'Month 12',
        'month4_text' => 'You cancel. Start over with someone new. Repeat the cycle.',
        'conclusion_text' => 'The problem isn\'t the people. The problem is the system. Human brains can only hold so much. Context disappears.',
        'conclusion_bold' => 'Core changes that.',
    ],
    'core_features' => [
        'pre_headline' => 'How Core Works',
        'headline' => 'The Nerdy Stuff, <span class="text-accent">Explained Simply.</span>',
        'intro' => 'We could throw around technical jargon. But you didn\'t start your business to become a tech expert. So here\'s how Core actually works in human language.',
        'f1_tech' => 'RAG Technology',
        'f1_title' => 'Memory That Never Quits',
        'f1_text1' => 'You know how you have to re-explain your business every time you talk to a new vendor? Core eliminates that.',
        'f1_text2' => 'We feed Core everything about your business: your services, your service areas, your pricing, your competitors, your best customers. It stores all of it and can instantly access it whenever we\'re building something for you.',
        'f1_example' => 'When we write a Google Ad, Core already knows your service areas, average ticket price, what makes you different, and which messaging worked best last time.',
        'f2_tech' => 'MCP Architecture',
        'f2_title' => 'Specialists That Scale',
        'f2_text1' => 'Imagine cloning your best employee and having them handle different parts of your marketing simultaneously. That\'s what Core does.',
        'f2_text2' => 'We\'ve built specialized AI "agents" for different tasks: one writes ad copy, one analyzes competitors, one optimizes campaigns, one researches keywords. They all share knowledge about your business.',
        'f2_example' => 'Instead of one generalist trying to do everything, you get a team of specialists working together — powered by AI, supervised by humans.',
        'f3_tech' => 'Vector Databases',
        'f3_title' => 'Knowledge That Compounds',
        'f3_text1' => 'Most agencies build campaigns with no foundation. Each month stands alone. Nothing stacks. Nothing compounds.',
        'f3_text2' => 'Core remembers everything — patterns, connections, and insights that humans would miss. Like: "Ads mentioning \'same-day service\' performed 34% better in summer months for this client."',
        'f3_example' => 'Every month, your marketing gets smarter because Core builds on everything that came before. No more reinventing the wheel.',
    ],
    'core_results' => [
        'pre_headline' => 'The Results',
        'headline' => 'Not Just Features. <span class="text-accent">Results.</span>',
        'card1_title' => 'Faster Launches',
        'card1_text' => 'Traditional agencies take weeks. Core lets us move in days because we\'re not starting from scratch.',
        'card2_title' => 'Better Targeting',
        'card2_text' => 'Core analyzes your market, competitors, and customers to find people most likely to book.',
        'card3_title' => 'Consistent Quality',
        'card3_text' => 'Every piece of content sounds like it came from someone who knows your business. Because Core does.',
        'card4_title' => 'Compounding Returns',
        'card4_text' => 'Your marketing improves month over month. The longer we work together, the better it gets.',
        'card5_title' => 'Real Attribution',
        'card5_text' => 'Core tracks every lead to its source. You\'ll always know what\'s working and what\'s not.',
        'card6_title' => 'Human Oversight',
        'card6_text' => 'AI handles the heavy lifting. Humans handle strategy, creativity, and quality control.',
    ],
    'core_faq' => [
        'pre_headline' => 'FAQ',
        'headline' => 'Questions About <span class="text-accent">Core.</span>',
        'q1' => 'Is this just ChatGPT with a different name?',
        'a1' => 'No. ChatGPT is a general-purpose tool. Core is a custom system we built specifically for local service business marketing. It has specialized agents, proprietary workflows, and a knowledge base tailored to your industry.',
        'q2' => 'Will AI replace the people working on my account?',
        'a2' => 'No. AI handles the grunt work: research, analysis, optimization. Humans handle strategy, creativity, and quality control. You get a team, not a robot.',
        'q3' => 'How long does it take to see results?',
        'a3' => 'It depends. Google Ads? We can make impactful changes quickly. SEO? That takes months. We\'ll give you an honest timeline after we analyze your situation — not before.',
        'q4' => 'Do I need to understand any of this technology?',
        'a4' => 'Not at all. You just need to know your business. We handle the rest.',
    ],
    'core_cta' => [
        'headline' => 'Ready to Put Core to Work?',
        'subtitle' => 'Stop competing against companies with bigger budgets. Core levels the playing field.',
        'cta_primary' => 'Schedule a Demo',
        'cta_secondary' => 'Talk to Our Team',
    ],
];
