<?php
return [
    'hero' => [
        'headline_line1' => 'AI-Powered',
        'headline_line2' => 'Human-Led',
        'headline_line3' => 'Built for Service Businesses',
        'subtitle' => 'We combine proprietary AI with real human expertise to help local service businesses dominate their markets. More leads. More booked jobs. Zero guesswork.',
        'cta_primary_text' => "Let's Talk Growth",
        'cta_secondary_text' => 'See How Core Works',
    ],
    'social_proof' => [
        'stat1_number' => '15+',
        'stat1_label' => 'Years in Business',
        'stat2_number' => '700+',
        'stat2_label' => 'Clients Served',
        'stat3_number' => '$125M+',
        'stat3_label' => 'Revenue Generated',
    ],
    'problem' => [
        'pre_headline' => 'The Problem',
        'headline' => "You've Outgrown Your Marketing. Your Marketing Hasn't Caught Up.",
        'paragraph1' => "You've built a real business. A growing team. Revenue that puts you in a different league than most of your competitors.",
        'paragraph2' => "But your marketing? <strong>It's stuck in 2019.</strong>",
        'paragraph3' => 'Maybe you\'ve got an agency that claims they "use AI" but all they\'re doing is copying and pasting from ChatGPT like everyone else. Maybe you\'ve tried a few vendors and the results were... fine. Generic. Forgettable.',
        'paragraph4' => "Here's the reality: most marketing agencies haven't evolved. They're running the same playbooks they ran five years ago, just with a few AI buzzwords sprinkled on top.",
        'highlight' => 'We are.',
    ],
    'core' => [
        'pre_headline' => 'Introducing Core',
        'headline' => 'AI That Learns Your Business.',
        'headline_accent' => 'Humans That Give a Damn.',
        'subtitle' => 'Core is our proprietary AI marketing engine built specifically for home service businesses like yours.',
        'card1_title' => 'It Remembers Everything',
        'card1_text' => 'Core connects to your business data and keeps it all organized. When we write an ad or build a landing page, Core already knows your business inside and out.',
        'card1_translation' => 'Translation: No more repeating yourself to marketers who forgot what you told them last month.',
        'card2_title' => 'It Gets Smarter Over Time',
        'card2_text' => 'Every campaign, every lead, every conversion teaches Core what works for YOUR market. Your marketing improves month over month.',
        'card2_translation' => 'Translation: Your marketing compounds. It doesn\'t just run in circles.',
        'card3_title' => 'Humans Stay in the Loop',
        'card3_text' => 'AI handles the heavy lifting. But real strategists review every campaign and make sure nothing goes out that doesn\'t meet our standards.',
        'card3_translation' => "Translation: You'll never get robot garbage with your logo slapped on it.",
        'cta_text' => 'See Core in Action',
    ],
    'services' => [
        'pre_headline' => 'What We Do',
        'headline' => 'Full-Service Marketing.',
        'headline_accent' => 'AI-Accelerated.',
        'subtitle' => 'We become your marketing department powered by technology that gives you an unfair advantage.',
        'card1_title' => 'SEO',
        'card1_text' => 'Get found when customers search for services in your area. Core identifies the exact keywords your competitors are ranking for and builds a strategy to outrank them.',
        'card2_title' => 'Google Ads',
        'card2_text' => "Stop wasting ad spend on clicks that don't convert. Our AI optimizes bids, tests ads, and targets the searches that actually turn into booked jobs.",
        'card3_title' => 'Meta Ads',
        'card3_text' => 'Reach customers before they even know they need you. Core builds audiences based on real data so your ads hit the right people at the right time.',
        'card4_title' => 'Website Design',
        'card4_text' => 'Your website should be your hardest-working salesperson. We build fast, conversion-focused sites designed to turn visitors into leads.',
    ],
    'differentiators' => [
        'pre_headline' => 'Why Agile & Co',
        'headline' => "We Aren't Like the Shitty Agencies",
        'headline_accent' => "You've Worked With.",
        'subtitle' => 'Four reasons service businesses choose us over traditional agencies.',
        'item1_title' => 'Proprietary AI, Not Off-the-Shelf Tools',
        'item1_text' => "Core isn't ChatGPT with a logo. It's a custom-built system using MCP architecture, RAG retrieval, and vector databases designed specifically for service business marketing.",
        'item2_title' => 'No Long-Term Contracts',
        'item2_text' => "We don't lock you in. You stay because we perform, not because you're stuck. If we're not delivering, you can walk. That's how confident we are.",
        'item3_title' => 'Real Attribution, Real Results',
        'item3_text' => "We track every lead to its source and optimize campaigns based on sales, not just leads. Clicks don't pay the bills. Booked jobs do.",
        'item4_title' => 'Local Service Business Specialists',
        'item4_text' => 'We specialize in local service-based businesses. From contractors and clinics to auto shops and med spas, we understand the unique challenges of marketing a service business.',
    ],
    'testimonials' => [
        'headline' => "Don't Take Our Word for It.",
        'quote1_text' => 'Our client acquisition cost was roughly $27,000 per client before we started with them. This channel alone is blowing that out of the water.',
        'quote1_author' => 'Infoplus Commerce',
        'quote2_text' => "We were getting visits in the low hundreds daily. We're now getting 6,500 visits a month and generating 15-20% of our business online.",
        'quote2_author' => 'Mulligan Funding',
        'quote3_text' => "They're very thorough. They take the time to understand our goals and protect us from spinning our wheels on things that don't make sense.",
        'quote3_author' => 'Custom Design & Construction',
        'quote4_text' => 'Agile & Co. has produced promising, measurable results quickly. We now have a lower cost per acquisition and higher qualified lead rate.',
        'quote4_author' => 'Employee Culture Platform',
    ],
    'process' => [
        'pre_headline' => 'How It Works',
        'headline' => 'Getting Started is',
        'headline_accent' => 'Simple.',
        'step1_title' => 'Discovery Call',
        'step1_text' => 'We learn about your business, your goals, and your current marketing. No pitch. No pressure.',
        'step2_title' => 'Custom Strategy',
        'step2_text' => 'We build a marketing plan powered by Core tailored to your services, market, and budget.',
        'step3_title' => 'Launch & Optimize',
        'step3_text' => 'Campaigns go live. Core starts learning. Every month, your marketing gets smarter and more profitable.',
        'cta_text' => 'Book Your Discovery Call',
    ],
    'final_cta' => [
        'headline' => 'Ready to Stop Guessing and Start Growing?',
        'subtitle' => "You've built something real. Let's make sure your marketing matches.",
        'cta_text' => 'Schedule a Call',
    ],
];
