<?php
return [
    // =========================================================================
    // LISTING PAGE (industries.php)
    // =========================================================================
    'listing' => [
        'listing_hero' => [
            'headline' => 'Industries',
            'headline_accent' => 'We Serve.',
            'subtitle' => 'AI-powered marketing built for local service businesses. We understand your industry, your customers, and what it takes to grow.',
            'cta_primary' => 'Get a Free Marketing Audit',
        ],
        'listing_grid' => [
            'card1_title' => 'HVAC',
            'card1_text' => 'Fill your schedule year-round with AI-powered marketing built for heating and cooling companies.',
            'card2_title' => 'Plumbing',
            'card2_text' => 'Generate consistent leads for your plumbing business with marketing that drives real booked jobs.',
            'card3_title' => 'Electrical',
            'card3_text' => 'Reach homeowners searching for electrical services with targeted campaigns that convert.',
            'card4_title' => 'Home Remodeling',
            'card4_text' => 'Win more renovation projects with marketing that showcases your craftsmanship.',
            'card5_title' => 'Residential Moving',
            'card5_text' => 'Book more moves with marketing that reaches customers at the right moment.',
            'card6_title' => 'Deck Contractors',
            'card6_text' => 'Generate quality leads for deck building and outdoor living projects.',
            'card7_title' => 'Landscaping',
            'card7_text' => 'Grow your landscaping business with marketing that attracts the right customers.',
            'card8_title' => 'General Contractors',
            'card8_text' => 'Win more construction projects with marketing that builds trust and credibility.',
            'card9_title' => 'Automotive Repair',
            'card9_text' => 'Drive more customers to your shop with targeted local marketing.',
            'card10_title' => 'Med Spa',
            'card10_text' => 'Attract clients looking for aesthetic treatments with sophisticated marketing.',
            'card11_title' => 'Fencing',
            'card11_text' => 'Generate leads for fence installation and repair with targeted campaigns.',
        ],
        'listing_cta' => [
            'headline' => 'Don\'t See Your Industry?',
            'subtitle' => 'We work with many service businesses. Let\'s talk about how we can help yours grow.',
            'cta_primary' => 'Get in Touch',
        ],
    ],

    // =========================================================================
    // HVAC (industry-hvac.php) — Extended Template
    // =========================================================================
    'hvac' => [
        'hvac_hero' => [
            'badge' => 'HVAC Marketing',
            'headline' => 'Fill Your Schedule.',
            'headline_accent' => 'Dominate Your Market.',
            'subtitle' => 'AI-powered marketing built specifically for HVAC companies. More service calls. More installations. More revenue without the guesswork.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works for HVAC',
        ],
        'hvac_intro' => [
            'pre_headline' => 'We Get HVAC',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow an HVAC Business.',
            'paragraph1' => 'Running an HVAC company isn\'t easy. You\'re competing against national franchises with massive budgets. You\'re dealing with seasonality that makes revenue unpredictable. And you\'re trying to find good techs while managing a growing operation.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We work exclusively with service businesses and we\'ve helped HVAC companies like yours generate consistent leads, fill schedules, and grow revenue year-round.',
            'card_title' => 'HVAC Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know HVAC inside and out — the seasonality, the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'hvac_core' => [
            'pre_headline' => 'Powered by Core',
            'headline' => 'Our AI Engine, Built for',
            'headline_accent' => 'Your HVAC Business.',
            'intro_text' => 'Core is our proprietary AI engine that changes everything about how marketing gets done. It learns your business, your services, your service areas, your voice, and your competitors. Then it works alongside our team to execute marketing that sounds like you and converts like crazy.',
            'feature1_title' => 'Automated Audits',
            'feature1_text' => 'Technical audits, SEO audits, competitor analysis, and link intersect analysis run automatically.',
            'feature2_title' => 'Prioritized Strategy',
            'feature2_text' => 'Builds a prioritized plan of attack based on what will actually move the needle for your business.',
            'feature3_title' => 'Autonomous Fixes',
            'feature3_text' => 'Finds issues and fixes them autonomously with human oversight — no waiting around.',
            'feature4_title' => 'Compounding Results',
            'feature4_text' => 'Gets smarter every month, compounding results over time. The longer we work together, the better it gets.',
        ],
        'hvac_challenges' => [
            'pre_headline' => 'HVAC Challenges',
            'headline' => 'The Challenges Every',
            'headline_accent' => 'HVAC Owner Knows.',
            'card1_title' => 'Seasonality',
            'card1_text' => 'Summer crushes you with AC calls. Winter brings furnace emergencies. Spring and fall? Crickets.',
            'card1_solution' => 'We build campaigns that smooth out the peaks and valleys — promoting maintenance plans, tune-ups, and installations during slower seasons so your revenue stays consistent.',
            'card2_title' => 'Franchise Competition',
            'card2_text' => 'The big guys have million-dollar marketing budgets and national brand recognition.',
            'card2_solution' => 'Core levels the playing field. Our AI analyzes exactly how competitors are winning local searches — then builds a strategy to beat them at their own game.',
            'card3_title' => 'Finding Quality Leads',
            'card3_text' => 'You\'re tired of tire-kickers and price shoppers. You want customers who value quality work and actually book.',
            'card3_solution' => 'We target high-intent searches and build campaigns that attract customers looking for professionals — not the cheapest option on Craigslist.',
            'card4_title' => 'Proving ROI',
            'card4_text' => 'You\'ve spent money on marketing before. You\'re not sure what worked.',
            'card4_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'hvac_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for HVAC.',
            'intro' => 'We become your marketing department. Here\'s how we help HVAC companies grow:',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when homeowners search for AC repair, furnace replacement, and HVAC services in your area. Core handles the audits, builds the strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core analyzes which keywords convert to booked jobs and optimizes bids in real-time.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition and trust in your service area so you\'re the first call when homeowners need HVAC work. Core builds audiences based on real data — not guesswork.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build fast, conversion-focused sites that turn visitors into leads.',
        ],
        'hvac_timeline' => [
            'pre_headline' => 'What to Expect',
            'headline' => 'What Working With Us',
            'headline_accent' => 'Looks Like.',
            'step1_period' => 'Month 1',
            'step1_title' => 'Discovery & Foundation',
            'step1_text' => 'We learn your business inside and out. Core runs its audits. We build your strategy and get the foundation in place.',
            'step2_period' => 'Months 2-3',
            'step2_title' => 'Execution & Optimization',
            'step2_text' => 'Campaigns go live. Core starts learning what works for your market. We optimize aggressively based on real data.',
            'step3_period' => 'Months 4-6',
            'step3_title' => 'Momentum',
            'step3_text' => 'Results start compounding. Core gets smarter. Your marketing machine starts hitting its stride.',
            'step4_period' => 'Months 6-12',
            'step4_title' => 'Scale',
            'step4_text' => 'This is where it gets good. Core has deep knowledge of your business and market. Every month builds on the last. Results compound.',
            'step5_period' => 'Year 2+',
            'step5_title' => 'The Long Game',
            'step5_text' => 'Now you have historical data. Core identifies trends from the previous year, spots seasonal patterns, and predicts opportunities before they happen. We\'re not just reacting anymore — we\'re anticipating.',
            'bottom_text' => 'Give us 6-12 months to reach optimal results. Marketing isn\'t magic, and real growth takes time. But Core gets smarter every month, so the longer we work together, the better it gets.',
        ],
        'hvac_why' => [
            'pre_headline' => 'Why Us',
            'headline' => 'Built for HVAC.',
            'headline_accent' => 'Powered by AI.',
            'card1_title' => 'Service Business Specialists',
            'card1_text' => 'We\'re not learning your industry on your dime. We know HVAC — the seasonality, the services, the customer mindset.',
            'card2_title' => 'Core Gives You an Edge',
            'card2_text' => 'Our AI engine analyzes your market, your competitors, and your performance faster and deeper than any traditional agency.',
            'card3_title' => 'No Long-Term Contracts',
            'card3_text' => 'We earn your business every month. If we don\'t perform, you can leave.',
            'card4_title' => 'Real Attribution',
            'card4_text' => 'You\'ll always know what\'s working. We track every lead to its source and optimize for sales, not just clicks.',
        ],
        'hvac_faq' => [
            'pre_headline' => 'FAQ',
            'headline' => 'Questions About',
            'headline_accent' => 'HVAC Marketing.',
            'q1' => 'How long before I see results?',
            'a1' => 'The honest answer: it depends. Google Ads can generate leads quickly. SEO takes months. The real timeline depends on your competition, your current marketing foundation, your budget, and a dozen other factors. We\'ll give you an honest assessment after we analyze your situation — not before.',
            'q2' => 'What if I already have a marketing company?',
            'a2' => 'We\'re happy to do a free audit and show you what you might be missing. If your current agency is crushing it, great — we\'ll tell you. If there are gaps, we\'ll show you how to fix them.',
            'q3' => 'How do you handle seasonality?',
            'a3' => 'We build year-round strategies that capitalize on peak seasons (emergency repairs) while building consistent revenue during slower months (maintenance plans, off-season tune-ups).',
            'q4' => 'What\'s the minimum budget?',
            'a4' => 'It depends on your market and goals. We\'ll give you an honest assessment of what it takes to compete in your area — and we won\'t take your money if we don\'t think we can deliver.',
            'q5' => 'Do you work with franchise HVAC companies?',
            'a5' => 'Yes. We work with both independent contractors and franchise owners. Core adapts to your specific situation and competitive landscape.',
        ],
        'hvac_cta' => [
            'headline' => 'Ready to Grow Your HVAC Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free HVAC Marketing Audit',
            'cta_secondary' => 'Talk to an HVAC Marketing Specialist',
        ],
    ],

    // =========================================================================
    // PLUMBING (industry-plumbing.php) — Standard Template
    // =========================================================================
    'plumbing' => [
        'plumbing_hero' => [
            'badge' => 'Plumbing Marketing',
            'headline' => 'More Calls. More Jobs.',
            'headline_accent' => 'More Revenue.',
            'subtitle' => 'AI-powered marketing built specifically for plumbing companies. Emergency calls, service appointments, and installations — we help you get more of all of it.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'plumbing_intro' => [
            'pre_headline' => 'We Get Plumbing',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a plumbing business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Plumbing Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know plumbing inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'plumbing_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Plumbing Business Knows.',
            'card1_title' => 'Emergency Competition',
            'card1_text' => 'When a pipe bursts, customers Google and pick fast. If you\'re not at the top, you\'re not getting the call.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Lead Quality',
            'card2_text' => 'You\'re tired of price shoppers. You want customers who value quality work.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'plumbing_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Plumbing.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'plumbing_cta' => [
            'headline' => 'Ready to Grow Your Plumbing Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // ELECTRICAL (industry-electrical.php) — Standard Template
    // =========================================================================
    'electrical' => [
        'electrical_hero' => [
            'badge' => 'Electrical Marketing',
            'headline' => 'Power Up Your',
            'headline_accent' => 'Lead Generation.',
            'subtitle' => 'AI-powered marketing for electrical contractors. Panel upgrades, rewiring, emergency calls — we help you dominate your market.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'electrical_intro' => [
            'pre_headline' => 'We Get Electrical',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a electrical business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Electrical Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know electrical inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'electrical_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Electrical Business Knows.',
            'card1_title' => 'Safety-First Customers',
            'card1_text' => 'Homeowners want electricians they can trust. Building that trust online is critical.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Competitive Market',
            'card2_text' => 'You\'re competing against big companies with bigger budgets.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'electrical_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Electrical.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'electrical_cta' => [
            'headline' => 'Ready to Grow Your Electrical Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // REMODELING (industry-remodeling.php) — Standard Template
    // =========================================================================
    'remodeling' => [
        'remodeling_hero' => [
            'badge' => 'Home Remodeling Marketing',
            'headline' => 'Build Your Pipeline.',
            'headline_accent' => 'Grow Your Business.',
            'subtitle' => 'AI-powered marketing for remodeling contractors. Kitchen renovations, bathroom remodels, whole-home projects — we help you win more bids.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'remodeling_intro' => [
            'pre_headline' => 'We Get Home Remodeling',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a home remodeling business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Home Remodeling Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know home remodeling inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'remodeling_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Home Remodeling Business Knows.',
            'card1_title' => 'Long Sales Cycle',
            'card1_text' => 'Remodeling projects take time to close. You need a steady pipeline of qualified leads.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Showcasing Work',
            'card2_text' => 'Your craftsmanship speaks for itself — but only if customers see it.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'remodeling_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Home Remodeling.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'remodeling_cta' => [
            'headline' => 'Ready to Grow Your Home Remodeling Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // MOVING (industry-moving.php) — Standard Template
    // =========================================================================
    'moving' => [
        'moving_hero' => [
            'badge' => 'Residential Moving Marketing',
            'headline' => 'Fill Your Calendar.',
            'headline_accent' => 'Move More Customers.',
            'subtitle' => 'AI-powered marketing for moving companies. Local moves, long-distance relocations, and everything in between.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'moving_intro' => [
            'pre_headline' => 'We Get Residential Moving',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a residential moving business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Residential Moving Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know residential moving inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'moving_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Residential Moving Business Knows.',
            'card1_title' => 'Seasonal Demand',
            'card1_text' => 'Summer is packed. Winter is slow. You need consistent leads year-round.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Trust Issues',
            'card2_text' => 'Customers are trusting you with their belongings. They need to trust you first.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'moving_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Residential Moving.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'moving_cta' => [
            'headline' => 'Ready to Grow Your Residential Moving Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // DECK (industry-deck.php) — Standard Template
    // =========================================================================
    'deck' => [
        'deck_hero' => [
            'badge' => 'Deck Contractors Marketing',
            'headline' => 'Build More Decks.',
            'headline_accent' => 'Grow Your Business.',
            'subtitle' => 'AI-powered marketing for deck builders and outdoor living specialists. Custom decks, patios, and outdoor spaces.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'deck_intro' => [
            'pre_headline' => 'We Get Deck Contractors',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a deck contractors business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Deck Contractors Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know deck contractors inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'deck_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Deck Contractors Business Knows.',
            'card1_title' => 'Seasonal Business',
            'card1_text' => 'Deck season is short. You need to maximize leads during peak months.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Visual Portfolio',
            'card2_text' => 'Customers want to see your work before they call.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'deck_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Deck Contractors.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'deck_cta' => [
            'headline' => 'Ready to Grow Your Deck Contractors Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // LANDSCAPING (industry-landscaping.php) — Standard Template
    // =========================================================================
    'landscaping' => [
        'landscaping_hero' => [
            'badge' => 'Landscaping Marketing',
            'headline' => 'Grow Your Business.',
            'headline_accent' => 'Literally.',
            'subtitle' => 'AI-powered marketing for landscaping companies. Design, installation, maintenance — we help you cultivate more customers.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'landscaping_intro' => [
            'pre_headline' => 'We Get Landscaping',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a landscaping business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Landscaping Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know landscaping inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'landscaping_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Landscaping Business Knows.',
            'card1_title' => 'Seasonal Fluctuation',
            'card1_text' => 'Spring and summer are busy. Fall and winter? Not so much.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Recurring Revenue',
            'card2_text' => 'One-time projects are great. Maintenance contracts are better.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'landscaping_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Landscaping.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'landscaping_cta' => [
            'headline' => 'Ready to Grow Your Landscaping Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // GENERAL CONTRACTORS (industry-general-contractors.php) — Standard Template
    // =========================================================================
    'gc' => [
        'gc_hero' => [
            'badge' => 'General Contractors Marketing',
            'headline' => 'Win More Projects.',
            'headline_accent' => 'Build Your Reputation.',
            'subtitle' => 'AI-powered marketing for general contractors. New construction, renovations, and commercial projects.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'gc_intro' => [
            'pre_headline' => 'We Get General Contractors',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a general contractors business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'General Contractors Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know general contractors inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'gc_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'General Contractors Business Knows.',
            'card1_title' => 'Competitive Bidding',
            'card1_text' => 'You\'re competing against established companies for every project.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Trust & Credentials',
            'card2_text' => 'Big projects require big trust. Customers need to see your track record.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'gc_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for General Contractors.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'gc_cta' => [
            'headline' => 'Ready to Grow Your General Contractors Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // AUTOMOTIVE (industry-automotive.php) — Standard Template
    // =========================================================================
    'automotive' => [
        'automotive_hero' => [
            'badge' => 'Automotive Repair Marketing',
            'headline' => 'Drive More Customers',
            'headline_accent' => 'to Your Shop.',
            'subtitle' => 'AI-powered marketing for auto repair shops. Routine maintenance, major repairs, and everything under the hood.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'automotive_intro' => [
            'pre_headline' => 'We Get Automotive Repair',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a automotive repair business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Automotive Repair Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know automotive repair inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'automotive_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Automotive Repair Business Knows.',
            'card1_title' => 'Dealership Competition',
            'card1_text' => 'You\'re competing against dealership service centers with big marketing budgets.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Building Loyalty',
            'card2_text' => 'First-time customers are expensive. Repeat customers are profitable.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'automotive_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Automotive Repair.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'automotive_cta' => [
            'headline' => 'Ready to Grow Your Automotive Repair Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // MED SPA (industry-medspa.php) — Standard Template
    // =========================================================================
    'medspa' => [
        'medspa_hero' => [
            'badge' => 'Med Spa Marketing',
            'headline' => 'Attract More Clients.',
            'headline_accent' => 'Elevate Your Brand.',
            'subtitle' => 'AI-powered marketing for med spas and aesthetic clinics. Botox, fillers, laser treatments, and body contouring.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'medspa_intro' => [
            'pre_headline' => 'We Get Med Spa',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a med spa business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Med Spa Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know med spa inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'medspa_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Med Spa Business Knows.',
            'card1_title' => 'Sophisticated Clients',
            'card1_text' => 'Your clients expect sophistication in everything — including your marketing.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Treatment Education',
            'card2_text' => 'Clients need to understand treatments before they book.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'medspa_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Med Spa.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'medspa_cta' => [
            'headline' => 'Ready to Grow Your Med Spa Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],

    // =========================================================================
    // FENCING (industry-fencing.php) — Standard Template
    // =========================================================================
    'fencing' => [
        'fencing_hero' => [
            'badge' => 'Fencing Marketing',
            'headline' => 'Close More Sales.',
            'headline_accent' => 'Build More Fences.',
            'subtitle' => 'AI-powered marketing for fence installation companies. Privacy fences, chain link, ornamental — we help you fence in more customers.',
            'cta_primary' => 'Get a Free Marketing Audit',
            'cta_secondary' => 'See How Core Works',
        ],
        'fencing_intro' => [
            'pre_headline' => 'We Get Fencing',
            'headline' => 'We Know What It Takes to',
            'headline_accent' => 'Grow Your Business.',
            'paragraph1' => 'Running a fencing business isn\'t easy. You\'re competing against bigger companies with larger budgets. You\'re managing operations while trying to grow. And finding good leads is harder than ever.',
            'paragraph2' => 'Marketing shouldn\'t be another headache.',
            'paragraph3' => 'That\'s where we come in. We specialize in service businesses and we\'ve helped companies like yours generate consistent leads and grow revenue.',
            'card_title' => 'Fencing Specialists',
            'card_text' => 'We\'re not learning your industry on your dime. We know fencing inside and out — the services, the customer mindset, and what actually drives booked jobs.',
        ],
        'fencing_challenges' => [
            'pre_headline' => 'Your Challenges',
            'headline' => 'Challenges Every',
            'headline_accent' => 'Fencing Business Knows.',
            'card1_title' => 'Seasonal Rush',
            'card1_text' => 'Spring fence season is chaos. You need a steady pipeline of quotes.',
            'card1_solution' => 'Core analyzes your market and competitors to build campaigns that target the right customers at the right time.',
            'card2_title' => 'Visual Proof',
            'card2_text' => 'Customers want to see your work before they request a quote.',
            'card2_solution' => 'We track every lead to its source. You\'ll know exactly which campaigns are driving calls, bookings, and revenue.',
        ],
        'fencing_services' => [
            'pre_headline' => 'Our Services',
            'headline' => 'Full-Service Marketing',
            'headline_accent' => 'for Fencing.',
            'card1_title' => 'SEO',
            'card1_text' => 'Get found when customers search for your services. Core handles audits, builds strategy, and executes automatically.',
            'card2_title' => 'Google Ads',
            'card2_text' => 'Show up at the top of search results instantly. Core optimizes bids based on what actually converts.',
            'card3_title' => 'Meta Ads',
            'card3_text' => 'Build brand recognition in your service area. Be the first call when customers need your services.',
            'card4_title' => 'Website Design',
            'card4_text' => 'Your website should be your best salesperson. We build sites that turn visitors into leads.',
        ],
        'fencing_cta' => [
            'headline' => 'Ready to Grow Your Fencing Business?',
            'subtitle' => 'You\'ve built something real. Let\'s make sure your marketing matches.',
            'cta_primary' => 'Get Your Free Marketing Audit',
            'cta_secondary' => 'Talk to a Specialist',
        ],
    ],
];
