<?php
return [
    'seo' => [
        'seo_hero' => [
            'pre_headline' => 'SEO Services',
            'headline' => 'Get Found. Get Chosen.',
            'headline_accent' => 'Get Booked.',
            'subtitle' => 'AI-powered SEO that puts your business in front of customers actively searching for your services. More visibility. More clicks. More jobs.',
            'cta_primary' => 'Get a Free SEO Audit',
            'cta_secondary' => 'See How Core Powers SEO',
        ],
        'seo_core_intro' => [
            'pre_headline' => 'How Core Transforms SEO',
            'headline' => 'SEO,',
            'headline_accent' => 'Supercharged by AI.',
            'paragraph1' => 'Most agencies run SEO the old way. Manual audits. Gut-feel strategies. Monthly reports that tell you what happened but not what to do next.',
            'paragraph2' => 'We built something different.',
            'paragraph3' => 'Core, our proprietary AI engine, was designed to make SEO faster, smarter, and more effective. It runs technical audits, SEO audits, competitor analysis, and link intersect analysis automatically. Then it builds a prioritized plan of attack.',
            'paragraph4' => "But here's where it gets interesting: Core doesn't just find issues. It fixes them. Autonomously. With human oversight to make sure nothing goes live without approval.",
        ],
        'seo_acronyms' => [
            'pre_headline' => 'The New SEO Landscape',
            'headline' => 'AEO. GEO. AIO.',
            'headline_accent' => "Let's Cut Through the Noise.",
            'intro' => 'The SEO world loves acronyms. Every year there\'s a new one. Here\'s what they actually mean:',
            'card1_abbr' => 'AEO',
            'card1_name' => 'Answer Engine Optimization',
            'card1_text' => 'Optimizing your content to appear in featured snippets, "People Also Ask" boxes, and direct answers at the top of search results.',
            'card2_abbr' => 'GEO',
            'card2_name' => 'Generative Engine Optimization',
            'card2_text' => "Optimizing for AI-powered search experiences like Google's AI Overviews, ChatGPT, and Perplexity.",
            'card3_abbr' => 'AIO',
            'card3_name' => 'AI Optimization',
            'card3_text' => 'Making sure your business shows up when AI tools are generating answers and recommendations.',
            'truth_title' => "Here's the truth:",
            'truth_text' => "These are all variations of the same core work. Good SEO has always been about understanding what people are searching for, creating content that answers their questions, and building authority. The platforms are evolving. AI is changing how people find information. But the fundamentals? They're the same. What's different is that you now need a system that can keep up with all of it. That's Core.",
        ],
        'seo_process' => [
            'pre_headline' => 'Our Process',
            'headline' => 'How We Build Your',
            'headline_accent' => 'SEO Strategy.',
            'step1_title' => 'The Audits',
            'step1_text' => 'Core crawls your entire website to identify issues and opportunities. Technical problems, content gaps, competitor weaknesses — we find it all.',
            'step2_title' => 'The Priority List',
            'step2_text' => 'Core takes everything from the audits and builds a prioritized action plan. Not a generic checklist — a strategic roadmap based on what will drive the biggest results for YOUR business.',
            'step3_title' => 'Execution',
            'step3_text' => "This is where Core shines. It doesn't just hand you a to-do list. Core executes — technical fixes, on-page optimization, content recommendations — all with human oversight.",
            'step4_title' => 'Ongoing Optimization',
            'step4_text' => "SEO isn't a project. It's a process. Core continuously monitors your rankings, identifies new opportunities, and keeps your strategy evolving as search evolves.",
        ],
        'seo_services' => [
            'pre_headline' => "What's Included",
            'headline' => 'Everything You Need',
            'headline_accent' => 'to Rank.',
            'card1_title' => 'Technical SEO',
            'card1_text' => 'Site speed optimization, mobile performance, crawl error fixes, schema markup, site architecture improvements.',
            'card2_title' => 'On-Page Optimization',
            'card2_text' => 'Title tags, meta descriptions, header structure, internal linking, keyword optimization across all pages.',
            'card3_title' => 'Content Strategy',
            'card3_text' => 'Blogging, service pages, location pages, FAQ content, and everything else that drives organic traffic.',
            'card4_title' => 'Local SEO',
            'card4_text' => 'Google Business Profile optimization, citation management, local pack strategy, review generation.',
            'card5_title' => 'Link Building',
            'card5_text' => 'Strategic outreach, digital PR, link intersect campaigns, authority building.',
            'card6_title' => 'Reporting & Attribution',
            'card6_text' => 'Full attribution on every lead. Clear, actionable reports. We optimize based on sales, not just traffic.',
        ],
        'seo_faq' => [
            'pre_headline' => 'FAQ',
            'headline' => 'SEO Questions,',
            'headline_accent' => 'Answered.',
            'q1' => 'How long does SEO take to work?',
            'a1' => "The honest answer: it depends. Your competition, your current site health, your budget, and a dozen other factors all play a role. Some clients see movement in weeks. Others take months to break through. We'll give you a realistic timeline after we analyze your situation — not before.",
            'q2' => 'What about ranking on AI tools like ChatGPT and Perplexity?',
            'a2' => 'Yes, we optimize for LLMs. Core is built to analyze how AI tools source and generate information. We structure your content, build your authority, and optimize your digital presence so you show up when AI is answering questions about your services.',
            'q3' => 'How is this different from what I\'ve tried before?',
            'a3' => "Core. Our AI engine runs audits, finds opportunities, and executes fixes autonomously with human oversight. It's faster, smarter, and more thorough than any traditional agency approach. And it compounds over time.",
            'q4' => 'Do I need a new website?',
            'a4' => 'Not necessarily. We can optimize most existing sites. If your site has fundamental issues holding you back, we\'ll tell you — and we can help with that too.',
        ],
        'seo_cta' => [
            'headline' => 'Ready to Get Found?',
            'subtitle' => 'Your competitors are ranking. Your customers are searching. Let\'s make sure they find you.',
            'cta_primary' => 'Get Your Free SEO Audit',
            'cta_secondary' => 'Talk to a Strategist',
        ],
    ],
    'gads' => [
        'gads_hero' => [
            'pre_headline' => 'Google Ads Services',
            'headline' => 'Stop Wasting Ad Spend.',
            'headline_accent' => 'Start Booking Jobs.',
            'subtitle' => 'AI-powered Google Ads management that puts your business at the top of search results and turns clicks into booked jobs. Not just traffic. Revenue.',
            'cta_primary' => 'Get a Free Google Ads Audit',
            'cta_secondary' => 'See How Core Powers Google Ads',
        ],
        'gads_core_intro' => [
            'pre_headline' => 'How Core Transforms Google Ads',
            'headline' => 'Google Ads,',
            'headline_accent' => 'Optimized by AI.',
            'paragraph1' => "Most agencies manage Google Ads the old way. Set up a campaign. Check in once a month. Send you a report full of impressions and clicks that don't mean anything.",
            'paragraph2' => 'We built something different.',
            'paragraph3' => 'Core, our proprietary AI engine, was designed to make Google Ads faster, smarter, and more profitable. It analyzes which keywords actually convert to booked jobs, optimizes bids in real-time, and kills underperforming ads before they waste your budget.',
            'paragraph4' => "But here's the key: Core doesn't optimize for clicks. It optimizes for sales. Because clicks don't pay the bills. Booked jobs do.",
        ],
        'gads_comparison' => [
            'headline' => 'Why Most Google Ads Campaigns',
            'headline_accent' => 'Fail.',
            'bad_label' => 'Typical Agency Approach',
            'bad1' => 'Set up campaigns based on "best practices"',
            'bad2' => 'Optimize for clicks and impressions',
            'bad3' => 'Send reports full of vanity metrics',
            'bad4' => 'Blame "the algorithm" when results don\'t come',
            'bad5' => 'Same playbook for every client',
            'good_label' => 'Our Approach',
            'good1' => 'Track every lead to its source with full attribution',
            'good2' => 'Know which keywords, ads, and campaigns drive actual revenue',
            'good3' => 'Optimize for sales, not clicks or impressions',
            'good4' => 'Core learns YOUR business specifically',
            'good5' => 'Real-time optimization, not monthly check-ins',
            'bottom_text' => 'The difference? A thousand clicks means nothing if nobody books a job.',
        ],
        'gads_process' => [
            'pre_headline' => 'Our Process',
            'headline' => 'How We Build Your',
            'headline_accent' => 'Google Ads Strategy.',
            'step1_title' => 'Audit & Analysis',
            'step1_text' => 'Core analyzes your existing campaigns (if any) to identify wasted spend, missed opportunities, and quick wins. We see exactly what your competitors are bidding on and where they\'re vulnerable.',
            'step2_title' => 'Campaign Build',
            'step2_text' => 'We build campaigns structured for performance. Search campaigns for high-intent keywords, Local Service Ads setup, remarketing to stay in front of past visitors, and landing pages designed to convert.',
            'step3_title' => 'Optimization',
            'step3_text' => 'This is where Core shines. It monitors performance continuously and makes adjustments in real-time. Bid adjustments, ad copy testing, negative keyword management, and budget reallocation to top performers.',
            'step4_title' => 'Attribution & Scaling',
            'step4_text' => "We track every lead to its source. You'll know exactly which campaigns drive revenue. Then we scale what works and cut what doesn't. More budget to winners. Less to losers.",
        ],
        'gads_services' => [
            'pre_headline' => "What's Included",
            'headline' => 'Everything You Need to',
            'headline_accent' => 'Win on Google.',
            'card1_title' => 'Search Campaigns',
            'card1_text' => 'High-intent keyword targeting for your core services. Show up when customers are actively searching.',
            'card2_title' => 'Local Service Ads',
            'card2_text' => 'Google Guaranteed placement at the very top of search results. Pay per lead, not per click.',
            'card3_title' => 'Display & Remarketing',
            'card3_text' => "Stay in front of visitors who didn't convert. Build brand recognition across the web.",
            'card4_title' => 'Landing Page Optimization',
            'card4_text' => 'Custom landing pages designed to convert clicks into calls. Core continuously tests and improves.',
            'card5_title' => 'Competitor Monitoring',
            'card5_text' => 'Real-time tracking of competitor ads, bids, and strategies so you stay ahead.',
            'card6_title' => 'Reporting & Attribution',
            'card6_text' => "Full attribution on every lead. We optimize based on sales, not just clicks. You'll always know what's driving revenue.",
        ],
        'gads_faq' => [
            'pre_headline' => 'FAQ',
            'headline' => 'Google Ads Questions,',
            'headline_accent' => 'Answered.',
            'q1' => 'How long does it take to see results?',
            'a1' => 'Google Ads can generate leads quickly, often within the first week. But optimization takes time. Give us 60-90 days to really dial in your campaigns and find what works for your market.',
            'q2' => 'How much should I budget for Google Ads?',
            'a2' => "It depends on your market and goals. Competitive markets require more spend to compete. We'll give you an honest assessment of what it takes to win in your area and we won't take your money if we don't think we can deliver.",
            'q3' => "What's the difference between Google Ads and Local Service Ads?",
            'a3' => 'Google Ads (Search) charges per click. Local Service Ads charges per lead and shows up at the very top of results with a "Google Guaranteed" badge. We typically recommend both, but it depends on your situation.',
            'q4' => 'How is this different from what I\'ve tried before?',
            'a4' => "Core. Our AI engine optimizes based on sales, not clicks. Full attribution on every lead. We know which campaigns drive revenue and we optimize for that. Most agencies optimize for metrics that look good in reports but don't drive business.",
            'q5' => "What if I've been burned by PPC agencies before?",
            'a5' => "We get it. That's why we don't do long-term contracts. If we're not delivering, you can leave. Our job is to make your Google Ads profitable. If we can't do that, you shouldn't pay us.",
        ],
        'gads_cta' => [
            'headline' => 'Ready to Make Google Ads Work?',
            'subtitle' => "Your competitors are bidding on your keywords right now. Let's make sure you're winning.",
            'cta_primary' => 'Get Your Free Google Ads Audit',
            'cta_secondary' => 'Talk to a Strategist',
        ],
    ],
    'meta' => [
        'meta_hero' => [
            'pre_headline' => 'Meta Ads Services',
            'headline' => 'Build the Brand That',
            'headline_accent' => 'Gets the Call.',
            'subtitle' => "AI-powered Facebook and Instagram advertising that builds brand recognition and trust in your market. When customers need your services, you're the first name they think of.",
            'cta_primary' => 'Get a Free Meta Ads Audit',
            'cta_secondary' => 'See How Core Powers Meta Ads',
        ],
        'meta_core_intro' => [
            'pre_headline' => 'How Core Transforms Meta Ads',
            'headline' => 'Meta Ads,',
            'headline_accent' => 'Powered by AI.',
            'paragraph1' => 'Most agencies treat Facebook and Instagram ads like a guessing game. Throw some ads out there. See what sticks. Hope for the best.',
            'paragraph2' => 'We built something different.',
            'paragraph3' => 'Core, our proprietary AI engine, builds audiences based on real data, tests creative variations automatically, and optimizes campaigns for the metrics that actually matter.',
            'paragraph4' => "We understand that Meta isn't Google. People aren't searching for \"plumber near me\" on Instagram. So we focus on what Meta does best: building brand recognition and trust so that when customers DO need your services, you're the first call.",
        ],
        'meta_services' => [
            'pre_headline' => "What's Included",
            'headline' => 'Everything You Need to',
            'headline_accent' => 'Build Your Brand.',
            'card1_title' => 'Audience Development',
            'card1_text' => 'Custom audiences built on real data. Lookalikes based on your best customers. Retargeting for past visitors.',
            'card2_title' => 'Creative Production',
            'card2_text' => 'Scroll-stopping images and videos designed for the feed. Content that builds trust, not just impressions.',
            'card3_title' => 'Campaign Management',
            'card3_text' => 'Ongoing optimization, testing, and refinement. Core monitors performance and adjusts automatically.',
            'card4_title' => 'Brand Awareness',
            'card4_text' => 'Top-of-funnel campaigns that put your brand in front of customers in your service area.',
            'card5_title' => 'Retargeting',
            'card5_text' => "Stay in front of website visitors who didn't convert. Keep your brand top-of-mind until they're ready.",
            'card6_title' => 'Reporting & Attribution',
            'card6_text' => 'Full attribution tracking. We connect Meta activity to actual calls and booked jobs.',
        ],
        'meta_cta' => [
            'headline' => 'Ready to Build a Brand That Wins?',
            'subtitle' => "Your competitors are in the feed. Let's make sure customers remember you when it matters.",
            'cta_primary' => 'Get Your Free Meta Ads Audit',
            'cta_secondary' => 'Talk to a Strategist',
        ],
    ],
    'webdesign' => [
        'webdesign_hero' => [
            'pre_headline' => 'Website Design Services',
            'headline' => 'A Website That Works',
            'headline_accent' => 'as Hard as You Do.',
            'subtitle' => 'AI-assisted website design built specifically for service businesses. Fast. Conversion-focused. Designed to turn visitors into booked jobs.',
            'cta_primary' => 'Get a Free Website Audit',
            'cta_secondary' => 'See Our Process',
        ],
        'webdesign_core_intro' => [
            'pre_headline' => 'How We Build Better Websites',
            'headline' => 'AI-Assisted Design.',
            'headline_accent' => 'Human Craftsmanship.',
            'paragraph1' => 'Most web design agencies work the same way they did 10 years ago. Long discovery phases. Endless revisions. Months of back-and-forth.',
            'paragraph2' => 'We use AI differently.',
            'paragraph3' => "AI helps us research your competitors, generate copy variations, analyze what's working in your industry, and optimize every page for conversions. Then our designers and developers bring it to life with craftsmanship that AI can't replicate.",
            'paragraph4' => 'The result? Websites that launch faster, convert better, and actually drive business.',
        ],
        'webdesign_services' => [
            'pre_headline' => "What's Included",
            'headline' => 'Everything You Need',
            'headline_accent' => 'to Convert.',
            'card1_title' => 'Custom Design',
            'card1_text' => 'A website designed specifically for your business, your brand, and your market.',
            'card2_title' => 'Mobile-First',
            'card2_text' => 'Your site looks and works perfectly on every device. Most visitors are on phones.',
            'card3_title' => 'Service Pages',
            'card3_text' => 'Dedicated pages for every service you offer, optimized for SEO and conversions.',
            'card4_title' => 'Location Pages',
            'card4_text' => 'Pages targeting each city and area you serve. Critical for local SEO.',
            'card5_title' => 'Speed Optimization',
            'card5_text' => 'Fast load times that improve user experience, conversions, and search rankings.',
            'card6_title' => 'Analytics & Tracking',
            'card6_text' => 'Full tracking setup so you know exactly how your website performs.',
        ],
        'webdesign_timeline' => [
            'pre_headline' => 'Our Timeline',
            'headline' => 'What to',
            'headline_accent' => 'Expect.',
            'step1_period' => 'Week 1-2',
            'step1_title' => 'Discovery & Strategy',
            'step1_text' => 'We learn your business, analyze your market, and map out your site structure.',
            'step2_period' => 'Week 3-4',
            'step2_title' => 'Design',
            'step2_text' => 'You see design concepts. We refine based on your feedback until you love it.',
            'step3_period' => 'Week 5-6',
            'step3_title' => 'Development',
            'step3_text' => 'We build your site with clean code, fast load times, and all integrations.',
            'step4_period' => 'Week 7',
            'step4_title' => 'Testing & Launch',
            'step4_text' => 'We test everything, train you on updates, and launch your new website.',
            'step5_period' => 'Ongoing',
            'step5_title' => 'Optimization',
            'step5_text' => 'After launch, we monitor performance and continuously optimize for better conversions.',
        ],
        'webdesign_cta' => [
            'headline' => 'Ready for a Website That Actually Works?',
            'subtitle' => "Your website should be your hardest-working salesperson. Let's build one that converts.",
            'cta_primary' => 'Get Your Free Website Audit',
            'cta_secondary' => 'Talk to a Strategist',
        ],
    ],
];
